name: docker build

on:
  push:
    branches:
      - 'root'
      - 'runner'
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.MY_SF_SSH }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Check Out Repo 
        uses: actions/checkout@v3
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Login to Aliyun Packages
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.MY_ALI_USER }}
          password: ${{ secrets.MY_ALI_PASSWORD }}
      - name: Login to tx Packages
        uses: docker/login-action@v2
        with:
          registry: hkccr.ccs.tencentyun.com
          username: ${{ secrets.MY_TX_USER }}
          password: ${{ secrets.MY_TX_PASSWORD }}
      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.MY_HUB_USER }}
          password: ${{ secrets.MY_HUB_PASSWORD }}
      - name: build docker
        run: ./6.ci.sh

  

